version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8000 -t .
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/sqlite/database.sqlite
    depends_on:
      - sqlite

  sqlite:
    image: nouchka/sqlite3:latest
    ports:
      - "8191:8191"
    volumes:
      - ./sqlite:/db
    command: [ "tail", "/dev/null" ]

