version: '3.8'

services:
  # PHP-FPM service
  php:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/app.ini
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - PHP_IDE_CONFIG=serverName=php-framework
      - XDEBUG_MODE=off
      - APP_URL=http://nginx
    depends_on:
      - sqlite

  # Nginx web server
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # SQLite service
  sqlite:
    image: nouchka/sqlite3:latest
    ports:
      - "8191:8191"
    volumes:
      - ./database:/db