services:
  # PHP-FPM service for production
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      platforms:
        - "linux/amd64"
    # No volumes - everything is in the image for production
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - APP_URL=http://nginx
    depends_on:
      - sqlite

  # Nginx web server
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # SQLite service
  sqlite:
    image: nouchka/sqlite3:latest
    volumes:
      - ./database:/db